import { Noto_Sans_JP } from "next/font/google";

import { Providers } from "@/components/Providers";

import type { Metadata } from "next";

import "@/app/globals.css";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
  title: "Reminist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} bg-background pt-12 font-sans text-text antialiased md:pt-16`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
